sudo: required
dist: trusty

branches:
  only: master

language: java
jdk: oraclejdk8
services: postgresql 
script: mvn clean package
before_script: 
	- psql -c "CREATE DATABASE testing_db;" -U postgres
	- psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
        - cd ./server/

