sudo: required
dist: trusty

branches:
  only: master
  
services:
    - mysql

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - mvn clean package
      before_script:
        - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
        - cd ./server/

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./front/
      script:
        - npm run build
