sudo: required
dist: trusty

branches:
  only: master

language: java
jdk: oraclejdk8
services: mysql 
script: mvn clean package
before_script: 
        - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
        - cd ./server/

